### PR TITLE
refactor: add file extension on import paths

### PR DESCRIPTION
**Pull request by Xayanide**
This is not necessary to be merged, but if considerable and acceptable, going to take a while to review due to 84 changed files, otherwise, please state a concise reason why it shouldn't be merged, I would be happy to read it.

I think I should be PR'ing to `dev` branch but it is behind `master` *shrug*

## Testing
Refactoring is finished, compiles, but, not properly or fully tested.

## Single quotes on Every Import paths
Due to inconsistent use of single quotes and double quotes on import paths that I see in the code, 
I believe it is much better to stick to single quotes only for every import path, no longer needing to press shift to put double quotes.

## ~~File extension on Every Import paths~~ (Update: Reverted)
While it is true that module aggregation, using less things to type when importing, also takes less lines, makes it a much more convenient and many more, 
but, it makes it a bit difficult to track where each import came from which file on the imports list, 
needing to click a specific import to get its location making it a bit ambiguous to read in my opinion.

Will add `.js` extension on every import paths
because I think it is much more maintainable, less difficult to read and refactor in the future than it already is, 
as a result every wildcard exports, aggregating modules (e.g export *) will be removed, that means having to type and put the actual path for each future import.

This is just a huge refactor on imports, and the main code structure shall remain as is in this pull request, so, it shouldn't break or change anything for the end user in general.

---

Will:
- Add `.js` file extension on import paths
- Use single quotes instead of double quotes on imports that don't use it
- Include the changes at unused imports (e.g imports that were shown fading in the IDE in my case)
- Remove wildcard exports, aggregating modules (e.g export *)
- Add a newline at end of affected files that don't have it from the change.

Will not:
- Add `.js` file extension on package import paths (e.g installed NPM dependencies etc.)
- Remove unused imports (e.g imports that were shown fading in the IDE in my case)
- Reorganize imports (e.g imports that leads to the same file but on a different line)

Unless requested, I will do the desired changes in the "Will not" list.

Things to check:
- Missing imports.
- Wrong import paths.
- Imports that have no `.js` file extension on their import paths.
- Missing semicolons at end of import paths.
- Double quotes on import paths.

### CODE REVIEW

**Comment by Meowhal** [comment]
## Single quotes on Every Import paths
It is true that lack of uniformity may be a problem.
The reason why both are currently mixed is because VS-Code's import completion function uses single quotes and I use double quotes when I write by hand. As a Japanese keyboard user, double quotes are a little easier to press. Therefore, I usually use it.
It might be better to add ESLint and use only single quotes.

## File extension on Every Import paths
This project uses ts-node for testing and debugging.
If extensions are written in import, they will not work.
For example, the following commands will no longer work.
` npm run test `
I can't merge this PR until this issue is resolved.

**Comment by Xayanide** [comment]
> If extensions are written in import, they will not work.
I will consider this, I will revert it.

**Comment by Xayanide** [comment]
What do you think, should I re-pr this, the title is no longer matching its sole purpose.

**Comment by Meowhal** [comment]
Thanks for doing so much work.

**Pull request merged**
