### PR TITLE
Add `!rank` Command and Official Game Mode Name

### PR DESCRIPTION
**Pull request by ZeroPyrozen**
## Summary
- Adding `!rank` command to show player current rank on selected regulation game mode
- Add official game mode name for view on regulation breaking and `!r`/`!regulation` command (osu!, osu!taiko, osu!catch, and osu!mania)
- Add `!rank` to readme and command file
- Modify `MapMirrorLoader` class to `MiscLoader` to support more miscellaneous commands in the future
- Add `!version`/`!v` command to show bot current version.

### CODE REVIEW

**Comment by Meowhal** [comment]
Thanks for the request. 
The name of the game has many different aliases, and it is complicated.
Instead of representing Mode as a pair of "value" and "name", it might be better to have a property for each purpose, as you have added officialName.

By the way, I am currently unable to review the code for a while due to personal reasons. 
If you think the code is okay, I will merge the code.

**Comment by ZeroPyrozen** [comment]
Yes I've rechecked it and remove all comments and console debug.

**Comment by ZeroPyrozen** [comment]
Oh wait, maybe we can add `!version` command to check what version the host is using. So if it outdated, we can message the host to update. I will put it along `!info`

**Comment by ZeroPyrozen** [comment]
Ready to be merged 👍

**Comment by Meowhal** [comment]
Thanks a lot ZeroPyrozen,

**Pull request merged**
