### PR TITLE
chore: add clean and compile npm script

### PR DESCRIPTION
**Pull request by Xayanide**
**Description**
Not really necessary, just a basic all-in-one clean then compile script (basically `npm run clean` and `npm run build` together) instead of typing and entering `npm run clean`  which we have to wait, then type `npm run build` right after.

I am sure there is a better way to name that script, `build` was already taken so I named it `dist` for now.

### CODE REVIEW

**Comment by Meowhal** [comment]
should we also run eslint and prettier with `npm run build`?
In order to do so, I first need to clean about my dirty code.

**Comment by Xayanide** [comment]
> should we also run eslint and prettier with `npm run build`?
I think eslint alone will suffice in my opinion, and yes we can go with that or seperate lint into a different script `"lint": "eslint src --fix"`

**Comment by Xayanide** [comment]
There is an [Eslint VS Code Extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) if you haven't installed it, it shows you the errors and warnings to fix along the way in the code editor.

**Comment by Meowhal** [comment]
Installed. To be honest, I was hesitant to start working on it because of the number of errors. I'll try to follow your advice once I'm done the working on the env branch.

I originally separated clean and build to reduce compile time a bit, but for that I should use ts-node, and your suggestion is the best.

**Pull request merged**
